# Generated by Django 5.2 on 2025-05-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0004_alter_item_reported_by_alter_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Return', 'Return'), ('Not claimed', 'Not claimed'), ('Donated', 'Donated')], default='lost', max_length=20),
        ),
    ]
