# Generated by Django 5.2 on 2025-05-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0006_item_disposition_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Returned', 'Returned'), ('Claimed', 'Claimed'), ('Donated', 'Donated')], default='Unclaimed', max_length=50, null=True),
        ),
    ]
